services:
  medique-server:
    build:
      context: ./server
    container_name: medique-server
    env_file:
      - ./server/.env.example
    ports:
      - "4000:4000"
    restart: unless-stopped
